POST http://localhost:3003/api/blogs 
Content-Type: application/json

    {
        "title": "dfsdf",
        "author": "ghfgyf",
        "url": "tryrty.com",
        "likes": 20,
        "userId": "60dbdf2bbc44092dcc21df1b"
    }